---
title: "Mini-Project 2: Adventure 1"
author: Anael Kuperwajs Cohen, Juliet Kelson
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---


```{r}
library(dplyr)
library(ggplot2)
library(caret)
library(stringr)
library(tidyverse)
library(quanteda)
library(syuzhet)
source("miniProjFunctions.R")
```


\
\



## Part 1: Process the data

```{r}
buzzfeed <- read.csv("https://www.macalester.edu/~ajohns24/data/buzzfeed.csv")

buzzfeed <- buzzfeed %>% 
  mutate(title = as.character(title),
         text = as.character(text),
         url = as.character(url))

'%!in%' <- function(x, y)!('%in%'(x,y))
```



### New predictors

Our new predictors will be:

[x] 1. % Unique words
[x] 2. Flesch–Kincaid grade level
[ ] 3. Primary sentiment
[ ] 4. Secondary sentiment
[x] 5. ! ratio (to . ?)
[x] 6. Author Count
[x] 7. ! ratio (to . ?) in title
[x] 8. Word count
[x] 9. Sentence Count
[x] 10. Syllables
[x] 11. Upper-case word count in title
[x] 12. Word count in title
[ ] 13. Strength of primary sentiment
[ ] 14. Strength of secondary sentiment
[x] 15. Upper-case word count


5.
```{r}
buzzfeed <- buzzfeed %>% 
  mutate(exclamation_ratio = exclamation_ratio(text))
```

7.
```{r}
buzzfeed <- buzzfeed %>% 
  mutate(exclamation_ratio_title = exclamation_ratio(title))
```

8.
```{r}
buzzfeed <- buzzfeed %>% 
  mutate(total_words = str_count(text, " ") + 1)
```

12.
```{r}
buzzfeed <- buzzfeed %>% 
  mutate(total_words_title = str_count(title, " ") + 1)
```

1.
```{r}
buzzfeed <- buzzfeed %>% 
  mutate(unique_word_percent = pct_unique_words(text, total_words))
```

15.
```{r}
buzzfeed <- buzzfeed %>% 
  mutate(total_upper_case_words = str_count(text, "\\b[A-Z]{2,}\\b"))
```

11.
```{r}
buzzfeed <- buzzfeed %>% 
  mutate(total_upper_case_words_title = str_count(title, "\\b[A-Z]{2,}\\b"))
```

6.
```{r}
buzzfeed <- buzzfeed %>%
  mutate(authors = gsub("View All Posts,", "", authors)) %>%
  mutate(authors = gsub("View All Posts", "", authors)) %>%
  mutate(authors = gsub("Abc News,", "", authors)) %>%
  mutate(authors = gsub("Abc News", "", authors)) %>%
  mutate(authors = gsub("Cnn National Politics Reporter,", "", authors)) %>%
  mutate(authors = gsub("Cnn National Politics Reporter", "", authors)) %>%
  mutate(authors = gsub("Cnn Pentagon Correspondent,", "", authors)) %>%
  mutate(authors = gsub("Cnn Pentagon Correspondent", "", authors)) %>%
  mutate(authors = gsub("Latest Posts,", "", authors)) %>%
  mutate(authors = gsub("Latest Posts", "", authors)) %>%
  mutate(authors = gsub("Cnn White House Producer,", "", authors)) %>%
  mutate(authors = gsub("Cnn White House Producer", "", authors)) %>%
  mutate(authors = gsub("Cnn Senior Congressional Producer,", "", authors)) %>%
  mutate(authors = gsub("Cnn Senior Congressional Producer", "", authors)) %>%
  mutate(author_count = str_count(authors, ",") + 1) %>% 
  mutate(author_count = if_else(author_count == 0, 1, author_count)) %>% 
  mutate(authors = if_else(authors == "", "None", authors))
```

10.
```{r}
buzzfeed <- buzzfeed %>% 
  mutate(total_syllables = nsyllable(text))
```

9.
```{r}
buzzfeed <- buzzfeed %>% 
  mutate(total_sentences = nsentence(text))
```

2.
```{r}
buzzfeed <- buzzfeed %>% 
  mutate(readability_score = flesch_reading_ease(total_words, total_sentences, total_syllables))
```

3.
```{r}
buzzfeed <- buzzfeed %>% 
  rowwise() %>% 
  mutate(primary_sentiment = max_sentiment_type(text),
         primary_sentiment_value = max_sentiment_value(text))
```



\
\
\
\
\
\



## Part 2: Analyze


\
\
\
\
\
\



## Part 3: Summarize




\
\
\
\
\
\



## Part 4: Contributions

